// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class Department
{
    public int DepartmentID { get; set; }

    public string DepartmentName { get; set; }
}