// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class InvoiceItem
{
    public int InvoiceItemID { get; set; }

    public int InvoiceID { get; set; }

    public string ProductID { get; set; }

    public string SupplierProductCode { get; set; }

    public string SupplierDescription { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Product Product { get; set; }
}