// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class Invoice
{
    public int InvoiceID { get; set; }

    public string InvoiceNumber { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public decimal TotalAmount { get; set; }

    public int SupplierID { get; set; }

    public int PaymentStatusID { get; set; }

    public virtual ICollection<InvoiceItem> InvoiceItems { get; set; } = new List<InvoiceItem>();

    public virtual Supplier Supplier { get; set; }
}