// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APWeb.TempModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace APWeb.TempModels
{
    public partial interface ITempDbContextProcedures
    {
        Task<int> InsertProductMovementAsync(string OrderID, int? MovementID, int? MovementType, int? SourceStorageAreaID, int? DestinationStorageAreaID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertProductMovementItemAsync(string OrderID, int? MovementID, int? ProductItemID, int? SourceWarehouseLocationID, int? DestinationWarehouseLocationID, decimal? Quantity, decimal? UnitCost, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
