// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class Node
{
    public int NodeID { get; set; }

    public string NodeName { get; set; }
}