// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class Order
{
    public string OrderID { get; set; }

    public DateTime DraftDate { get; set; }

    public int OrderType { get; set; }

    public int SourceStorageAreaID { get; set; }

    public int DestinationStorageAreaID { get; set; }

    public int? SupplierID { get; set; }

    public int? StoreID { get; set; }

    public int OrderStatusID { get; set; }

    public DateTime SubmitDate { get; set; }

    public DateTime CompleteDate { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual OrderType OrderTypeNavigation { get; set; }

    public virtual ICollection<ProductMovement> ProductMovements { get; set; } = new List<ProductMovement>();

    public virtual Store Store { get; set; }

    public virtual Supplier Supplier { get; set; }
}