// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class OrderItem
{
    public string OrderID { get; set; }

    public int ProductItemID { get; set; }

    public int SourceWarehouseLocationID { get; set; }

    public int DestinationWarehouseLocationID { get; set; }

    public decimal UnitQty { get; set; }

    public decimal UnitCost { get; set; }

    public int UnitsPerPackage { get; set; }

    public int OrderItemStatusID { get; set; }

    public DateTime DraftDate { get; set; }

    public DateTime SubmitDate { get; set; }

    public DateTime CompleteDate { get; set; }

    public decimal TaxRate { get; set; }

    public virtual Order Order { get; set; }

    public virtual ProductItem ProductItem { get; set; }
}