// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class PO_Detail
{
    public string PO_ID { get; set; }

    public string Product_ID { get; set; }

    public int UnitsOnPO { get; set; }

    public decimal? UnitPODraftPrice { get; set; }

    public float? Discount { get; set; }

    public bool Reviewed { get; set; }

    public bool PriceApproved { get; set; }

    public bool UnitsApproved { get; set; }

    public bool ReceivedStatus { get; set; }

    public bool Status { get; set; }

    public int UnitsReceived { get; set; }

    public DateTime? ReceivingDate { get; set; }

    public string ReceivedBy { get; set; }

    public float? PriceReceived { get; set; }

    public int? UnitsPerPackage { get; set; }

    public bool? Taxable { get; set; }

    public double? TaxRate { get; set; }

    public DateTime? OrderingDate { get; set; }

    public string OrderedBy { get; set; }

    public double? UnitsOrdered { get; set; }

    public double? PriceOrdered { get; set; }

    public int PaidItems { get; set; }

    public int FreeItems { get; set; }

    public double? SRPRice { get; set; }

    public double? UnitsShipped { get; set; }

    public float? PriceShipped { get; set; }

    public bool? ShippedStatus { get; set; }

    public DateTime? ShippedDate { get; set; }

    public int? Confirm { get; set; }

    public int Store_ID { get; set; }

    public int? Transaction_ID { get; set; }
}