// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class ProductItem
{
    public int ItemID { get; set; }

    public string ItemDesc { get; set; }

    public string ItemSigningDesc { get; set; }

    public string ProductID { get; set; }

    public int SupplierID { get; set; }

    public decimal? UnitRetail { get; set; }

    public decimal? UnitCost { get; set; }

    public int? ItemStatus { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateTime? CreateTimeStamp { get; set; }

    public DateTime? UpdateTimeStamp { get; set; }

    public int? LeadTime { get; set; }

    public string SupplierProductCode { get; set; }

    public string SupplierProductDescription { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductMovementItem> ProductMovementItems { get; set; } = new List<ProductMovementItem>();

    public virtual Supplier Supplier { get; set; }
}