// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class Product
{
    public string Prod_Num { get; set; }

    public string Prod_Name { get; set; }

    public string Prod_Desc { get; set; }

    public decimal Unit_Cost { get; set; }

    public string Measure { get; set; }

    public int? OnSales { get; set; }

    public string Barcode { get; set; }

    public string Prod_Alias { get; set; }

    public short? Tax1App { get; set; }

    public short? Tax2App { get; set; }

    public string PackageSpec { get; set; }

    public decimal? SuggestSalePrice { get; set; }

    public double? NumPerPack { get; set; }

    public int? PriceMode { get; set; }

    public int? QtySale { get; set; }

    public int? QtySaleQty { get; set; }

    public double? QtySalePrice { get; set; }

    public string ModTimeStamp { get; set; }

    public string Department { get; set; }

    public string Last_Ord_Date { get; set; }

    public double On_Order { get; set; }

    public double Ord_Point { get; set; }

    public short isFood { get; set; }

    public string Source { get; set; }

    public string UPC { get; set; }

    public double? UnitSize { get; set; }

    public string UnitSizeUom { get; set; }

    public string CountryOfOrigin { get; set; }

    public int? EthnicGroupID { get; set; }

    public virtual ICollection<InvoiceItem> InvoiceItems { get; set; } = new List<InvoiceItem>();

    public virtual ICollection<ProductItem> ProductItems { get; set; } = new List<ProductItem>();
}