// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class StoreFloorLocation
{
    public int StoreLocationID { get; set; }

    public int StoreID { get; set; }

    public string Location { get; set; }

    public int LocationType { get; set; }

    public string Aisle { get; set; }

    public string Side { get; set; }

    public string Section { get; set; }

    public decimal? Capacity { get; set; }

    public int Active { get; set; }

    public virtual Store Store { get; set; }
}