// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class StoreFloorLocationType
{
    public int LocationTypeID { get; set; }

    public string LocationTypeDesc { get; set; }
}