// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.TempModels;

public partial class WarehouseStorageArea
{
    public int WarehouseStorageAreaID { get; set; }

    public int WarehouseID { get; set; }

    public string AreaType { get; set; }

    public int StoreID { get; set; }

    public string TemperatureZone { get; set; }

    public decimal AllocationSize { get; set; }

    public string WarehouseStorageAreaName { get; set; }

    public virtual Store Store { get; set; }

    public virtual Warehouse Warehouse { get; set; }

    public virtual ICollection<WarehouseStorageLocation> WarehouseStorageLocations { get; set; } = new List<WarehouseStorageLocation>();
}