// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.Models;

public partial class Inventory
{
    public int InventoryID { get; set; }

    public int ItemID { get; set; }

    public int LocationID { get; set; }

    public decimal CurrentStock { get; set; }

    public decimal ReorderPoint { get; set; }

    public decimal SafetyStock { get; set; }

    public DateTime LastReplenished { get; set; }

    public decimal CurrentCost { get; set; }

    public DateTime ModTime { get; set; }

    public virtual ProductItem Item { get; set; }

    public virtual WarehouseStorageLocation Location { get; set; }
}