// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.Models;

public partial class PO
{
    public string PO_ID { get; set; }

    public int Store_ID { get; set; }

    public int Buyer_ID { get; set; }

    public int Supplier_ID { get; set; }

    public string SupplierContact { get; set; }

    public DateTime? PODraftDate { get; set; }

    public string PONote { get; set; }

    public int? POStatus_ID { get; set; }

    public bool POComplete { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public DateTime? POApprovedDate { get; set; }

    public string DeliveryTo { get; set; }

    public decimal? Taxes { get; set; }

    public string Notes { get; set; }

    public string Invoice { get; set; }

    public byte[] Signature { get; set; }

    public string State { get; set; }

    public string Ordered_By { get; set; }

    public string Received_By { get; set; }

    public DateTime? Ordering_Date { get; set; }

    public DateTime? Ordered_Date { get; set; }

    public DateTime? Received_Date { get; set; }

    public byte[] Received_Signature { get; set; }

    public bool? SendToSupplier { get; set; }

    public DateOnly? Invoice_Date { get; set; }

    public string ShippedToWM { get; set; }

    public int? Combine { get; set; }
}