// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.Models;

public partial class ProductMovement
{
    public int MovementID { get; set; }

    public string OrderID { get; set; }

    public int MovementType { get; set; }

    public decimal Quantity { get; set; }

    public DateTime DraftDate { get; set; }

    public int SourceStorageAreaID { get; set; }

    public int? DestinationStorageAreaID { get; set; }

    public decimal TotalCost { get; set; }

    public int MovementStatusID { get; set; }

    public DateTime SubmitDate { get; set; }

    public DateTime CompleteDate { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<ProductMovementItem> ProductMovementItems { get; set; } = new List<ProductMovementItem>();
}