// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.Models;

public partial class Suppliers_Store
{
    public int Supplier_ID { get; set; }

    public int? Payment_Supplier_ID { get; set; }

    public string CompanyName { get; set; }

    public string Tel { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Addr { get; set; }

    public string Post_Code { get; set; }

    public string SafetyLicense { get; set; }

    public DateTime? Date { get; set; }

    public int Store_ID { get; set; }
}