// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.Models;

public partial class WarehouseStorageLocation
{
    public int WarehouseLocationID { get; set; }

    public int WarehouseStorageAreaID { get; set; }

    public int CoordinateX { get; set; }

    public int CoordinateY { get; set; }

    public int CoordinateZ { get; set; }

    public decimal Capacity { get; set; }

    public int Active { get; set; }

    public string LocationName { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual WarehouseStorageArea WarehouseStorageArea { get; set; }
}