// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APWeb.Models;

public partial class Warehouse
{
    public int WarehouseID { get; set; }

    public string WarehouseName { get; set; }

    public string Location { get; set; }

    public int StoreID { get; set; }

    public virtual ICollection<WarehouseStorageArea> WarehouseStorageAreas { get; set; } = new List<WarehouseStorageArea>();
}